const fortuneCookies = [
  "Conquer your fears or they will conquer you.",
  "Rivers need springs.",
  "Do not fear what you don't know.",
  "You will have a pleasant surprise.",
  "Whenever possible, keep it simple.",
  "You will find great fortune in unexpected places.",
  "Adventure awaits those who seek it.",
  "A fresh start will put you on your way.",
  "A lifetime friend shall soon be made.",
  "A lifetime of happiness lies ahead of you.",
  "A light heart carries you through all the hard times.",
  "A new perspective will come with the new year.",
  "A person is never too old to learn.",
  "A pleasant surprise is waiting for you.",
  "A smile is your personal welcome mat.",
  "A smooth long journey! Great expectations.",
  "A soft voice may be awfully persuasive.",
  "A truly rich life contains love and art in abundance.",
  "Accept something that you cannot change, and you will feel better.",
  "Adventure can be real happiness.",
  "Advice is like kissing. It costs nothing and is a pleasant thing to do.",
  "All the effort you are making will ultimately pay off.",
  "All the troubles you have will pass away very quickly.",
  "All your hard work will soon pay off.",
  "Allow compassion to guide your decisions.",
  "An acquaintance of the past will affect you in the near future.",
  "An agreeable romance might begin to take on the appearance.",
  "An important person will offer you support.",
  "An inch of time is an inch of gold.",
  "Any decision you have to make tomorrow is a good decision.",
  "At the touch of love, everyone becomes a poet.",
  "Be careful or you could fall for some tricks today.",
  "Beauty in its various forms appeals to you.",
  "Believe in yourself and others will too.",
  "Believe it can be done.",
  "Better ask twice than lose yourself once.",
  "Big journeys begin with a single step.",
  "Bigger things are coming.",
  "Business is a lot like playing tennis; if you don't serve well, you lose.",
  "Change is happening in your life, so go with the flow!",
  "Competence like yours is underrated.",
  "Congratulations! You are on your way.",
  "Do not be covered in sadness or be fooled in happiness they both must exist.",
  "Do not let ambitions overshadow small success.",
  "Do not make extra work for yourself.",
  "Do not underestimate yourself. Human beings have unlimited potentials.",
  "Don't just think, act!",
  "Don’t confuse recklessness with confidence.",
  "Don’t just spend time. Invest it.",
  "Don't let friends impose on you, work calmly and silently.",
  "Don’t let the past hold you back, you’re missing the good stuff.",
  "Don’t worry; prosperity will knock on your door soon.",
  "Each day, compel yourself to do something you would rather not do.",
  "Education is the ability to meet life’s situations.",
  "Embrace this love relationship you have!",
  "Emulate what you admire in your parents.",
  "Emulate what you respect in your friends.",
  "Every flower blooms in its own sweet time.",
  "Every wise man started out by asking many questions.",
  "Failure is the chance to do better next time.",
  "Fear and desire – two sides of the same coin.",
  "Feeding a cow with roses does not get extra appreciation.",
  "First think of what you want to do; then do what you have to do.",
  "For hate is never conquered by hate. Hate is conquered by love.",
  "Fortune Not Found: Abort, Retry, Ignore?",
  "From now on your kindness will lead you to success.",
  "Get your mind set – confidence will lead you on.",
  "Go for the gold today! You’ll be the champion of whatever.",
];

exports.getFortune = function () {
  const idx = Math.floor(Math.random() * fortuneCookies.length);
  return fortuneCookies[idx];
};
